"""Emit a single self-contained solver file for Kaggle.

Kaggle notebooks run offline, so the usual answer is to upload the repo as a
Dataset. This script removes that step: it walks the real import closure of
``src.kaggle_run`` (including the lazy imports that only fire during a solve),
embeds each module's source, and writes one Python file that unpacks itself
into a temp directory and puts it on ``sys.path``.

The package layout is preserved verbatim, so no import rewriting happens and
the bundled code is byte-identical to the repo's.

    python scripts/build_kaggle_bundle.py --out kaggle/arc_bundle.py
"""

from __future__ import annotations

import argparse
import base64
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Modules that need torch/transformers. The offline solver never touches them,
# and importing them on Kaggle would be a hard failure.
EXCLUDE = {"src.hrps.hf_compat", "src.hrps.model", "src.hrps.package"}

HEADER = '''"""ARC solver bundle - generated by scripts/build_kaggle_bundle.py. Do not edit.

Self-extracting: importing this module unpacks the `src` package into a temp
directory and prepends it to sys.path. Pure standard library, no network.

    import arc_bundle
    from src.kaggle_run import build_config, run
"""

import base64
import sys
import tempfile
import zlib
from pathlib import Path

_PAYLOAD = {
'''

FOOTER = '''}


def _install() -> Path:
    root = Path(tempfile.mkdtemp(prefix="arc_bundle_"))
    for rel, blob in _PAYLOAD.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(zlib.decompress(base64.b64decode(blob)))
    sys.path.insert(0, str(root))
    return root


BUNDLE_ROOT = _install()
'''


def import_closure() -> list[str]:
    """Module names under `src.` reached by a real solve, not just by import."""
    sys.path.insert(0, str(REPO_ROOT))
    from src.hrps.task import parse_task  # noqa: F401
    import src.kaggle_run  # noqa: F401

    # The LLM path too, so one bundle serves both notebooks. These modules
    # import torch lazily inside functions, so they cost nothing offline.
    import src.kaggle_llm_run  # noqa: F401
    import src.test_time_train  # noqa: F401
    from src.arc_solve import solve_task

    # Exercise the lazy paths (search stage L pulls in abstractions/language).
    probe = parse_task(
        "probe",
        {
            "train": [
                {"input": [[1, 2], [3, 4]], "output": [[4, 3], [2, 1]]},
                {"input": [[5, 6], [7, 8]], "output": [[8, 7], [6, 5]]},
            ],
            "test": [{"input": [[1, 1], [2, 2]]}],
        },
        "test",
    )
    solve_task(probe, seconds=3.0)

    return sorted(
        name
        for name in sys.modules
        if (name == "src" or name.startswith("src.")) and name not in EXCLUDE
    )


def module_path(name: str) -> Path:
    parts = name.split(".")
    pkg = REPO_ROOT / Path(*parts) / "__init__.py"
    if pkg.is_file():
        return pkg
    return REPO_ROOT / Path(*parts[:-1]) / f"{parts[-1]}.py"


def build(out_path: Path) -> dict[str, int]:
    import zlib

    names = import_closure()
    entries: list[str] = []
    total = 0
    for name in names:
        path = module_path(name)
        if not path.is_file():
            continue
        rel = path.relative_to(REPO_ROOT).as_posix()
        raw = path.read_bytes()
        total += len(raw)
        blob = base64.b64encode(zlib.compress(raw, 9)).decode("ascii")
        entries.append(f'    "{rel}": (\n' + _wrap(blob) + "    ),\n")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(HEADER + "".join(entries) + FOOTER, encoding="utf-8")
    return {"modules": len(entries), "source_bytes": total, "bundle_bytes": out_path.stat().st_size}


def _wrap(blob: str, width: int = 96) -> str:
    return "".join(f'        "{blob[i : i + width]}"\n' for i in range(0, len(blob), width))


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="build the Kaggle solver bundle")
    p.add_argument("--out", default=str(REPO_ROOT / "kaggle" / "arc_bundle.py"))
    args = p.parse_args(argv)
    stats = build(Path(args.out))
    print(f"wrote {args.out}: {stats}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
